server:
  port: 8004
  servlet:
    context-path: /booking

spring:
  application:
    name: booking-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/02-booking-service-tingboxvn"
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-second: 10
    lease-expiration-duration-in-seconds: 30